
import type { DevelopmentDomain, ObservationContext } from './types';

// Language type
export type Language = 'tr' | 'en';

// Current language state
let currentLanguage: Language = 'tr';

// Initialize language from localStorage or browser
const initLanguage = (): Language => {
  if (typeof window !== 'undefined') {
    const stored = localStorage.getItem('app_language') as Language | null;
    if (stored === 'tr' || stored === 'en') return stored;
    // Auto-detect from browser
    const browserLang = navigator.language?.slice(0, 2);
    if (browserLang === 'en') return 'en';
  }
  return 'tr';
};

currentLanguage = initLanguage();

// Language setters/getters
export const setLanguage = (lang: Language): void => {
  currentLanguage = lang;
  if (typeof window !== 'undefined') {
    localStorage.setItem('app_language', lang);
  }
};

export const getLanguage = (): Language => currentLanguage;

// Development domains per language
export const DEVELOPMENT_DOMAINS: Record<Language, Record<string, string>> = {
  tr: {
    turkish: 'Türkçe',
    math: 'Matematik',
    science: 'Fen',
    social: 'Sosyal',
    motor_health: 'Hareket ve Sağlık',
    art: 'Sanat',
    music: 'Müzik',
  },
  en: {
    turkish: 'Turkish Language',
    math: 'Mathematics',
    science: 'Science',
    social: 'Social Studies',
    motor_health: 'Motor & Health',
    art: 'Art',
    music: 'Music',
  }
};

export const getDomains = (): Record<string, string> => DEVELOPMENT_DOMAINS[currentLanguage];

// Observation contexts per language
export const OBSERVATION_CONTEXTS: Record<Language, Record<ObservationContext, string>> = {
  tr: {
    classroom: 'Sınıf İçi',
    outdoor: 'Dış Mekan',
    home: 'Ev',
    other: 'Diğer',
  },
  en: {
    classroom: 'Classroom',
    outdoor: 'Outdoor',
    home: 'Home',
    other: 'Other',
  }
};

export const getContexts = (): Record<ObservationContext, string> => OBSERVATION_CONTEXTS[currentLanguage];

// Date locale helper
export const getDateLocale = (): string => currentLanguage === 'tr' ? 'tr-TR' : 'en-US';

// Translations
const translations: Record<Language, Record<string, string>> = {
  tr: {
    appName: 'PortfoAI',
    // Auth
    signInTitle: 'Giriş Yapın',
    signUpTitle: 'Hesap Oluşturun',
    signInDescription: 'Hesabınıza erişmek için e-posta ve parolanızı girin.',
    signUpDescription: 'Başlamak için yeni bir hesap oluşturun.',
    emailLabel: 'E-posta Adresi',
    passwordLabel: 'Parola',
    signInAction: 'Giriş Yap',
    signUpAction: 'Üye Ol',
    noAccountPrompt: 'Hesabınız yok mu?',
    haveAccountPrompt: 'Zaten hesabınız var mı?',
    switchToSignUp: 'Üye Olun',
    switchToSignIn: 'Giriş Yapın',
    signUpSuccess: 'Hesabınız oluşturuldu! Lütfen e-postanızı doğrulayın.',
    apiKeyError: 'Supabase API Anahtarı geçersiz veya eksik.',
    // General
    dashboard: 'Anasayfa',
    children: 'Çocuklar',
    observations: 'Gözlemler',
    settings: 'Ayarlar',
    signOut: 'Çıkış Yap',
    welcome: 'Hoş Geldiniz',
    // Landing / Auth
    landingHero: 'Yapay zeka destekli gözlem, analiz ve portfolyo yönetimi ile çocukların gelişimini profesyonelce takip edin.',
    smartAnalysisTitle: 'Akıllı Gözlem Analizi',
    smartAnalysisDesc: 'Yapay zeka ile otomatik değerlendirme ve öneriler',
    digitalPortfolioTitle: 'Dijital Portfolyo',
    digitalPortfolioDesc: 'Çocukların ürünlerini ve gelişimini dijital ortamda saklayın',
    anyDeviceTitle: 'Her Yerden Erişim',
    anyDeviceDesc: 'Telefon, tablet veya bilgisayardan kolayca ulaşın',
    createAccountTitle: 'Hesap Oluştur',
    welcomeTitle: 'Hoş Geldiniz',
    createAccountDesc: 'Yeni bir hesap oluşturun ve başlayın',
    signInDesc: 'Hesabınıza giriş yapın',
    yourName: 'Adınız',
    yourSurname: 'Soyadınız',
    schoolName: 'Okul Adı',
    secureSSL: 'SSL Şifreli',
    secureBadge: 'Güvenli',
    fastBadge: 'Hızlı',
    footerRights: '© 2025 PortfoAI - Tüm hakları saklıdır',
    haveAccountBtn: 'Zaten hesabınız var mı? Giriş yapın',
    noAccountBtn: 'Hesabınız yok mu? Kayıt olun',
    missingTeacherFields: 'Lütfen ad, soyad ve okul alanlarını doldurun.',
    recentObservations: 'Son Gözlemler',
    quickAccess: 'Hızlı Erişim',
    addChild: 'Çocuk Ekle',
    addObservation: 'Gözlem Ekle',
    editObservation: 'Gözlemi Düzenle',
    childList: 'Çocuk Listesi',
    searchChild: 'Çocuk ara...',
    noChildrenFound: 'Henüz hiç çocuk eklenmedi.',
    childProfile: 'Çocuk Profili',
    firstName: 'Adı',
    lastName: 'Soyadı',
    dob: 'Doğum Tarihi',
    age: 'Yaş',
    classroom: 'Sınıf',
    parentalConsent: 'Veli Onayı Alındı',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    edit: 'Düzenle',
    newObservationFor: 'için Yeni Gözlem',
    observationNote: 'Gözlem Notu',
    notePlaceholder: 'Çocuğun davranışları, sözleri ve etkileşimleri hakkında detaylı notlar...',
    developmentDomains: 'Beceri Alanları',
    selectDomains: 'İlgili beceri alanlarını seçin',
    context: 'Ortam',
    tags: 'Etiketler',
    tagsPlaceholder: 'Virgül ile ayırarak etiket ekleyin',
    addMedia: 'Fotoğraf/Video Ekle',
    submitObservation: 'Gözlemi Kaydet',
    consentYes: 'Evet',
    consentNo: 'Hayır',
    childDetail: 'Çocuk Detayları',
    profile: 'Profil',
    development: 'Gelişim',
    media: 'Medya',
    generateReport: 'Gelişim Raporu Oluştur',
    aiAnalysis: 'Yapay Zeka Analizi',
    getAnalysis: 'Analiz İste',
    summary: 'Özet',
    riskLevel: 'Risk Düzeyi',
    suggestions: 'Öğretmene Öneriler',
    domainScores: 'Alan Puanları',
    low: 'Düşük',
    medium: 'Orta',
    high: 'Yüksek',
    loading: 'Yükleniyor...',
    deleting: 'Siliniyor...',
    errorOccurred: 'Bir hata oluştu.',
    offlineWarning: 'Çevrimdışı moddas­ınız.',
    syncAttempt: 'Veriler senkronize ediliyor...',
    syncSuccess: 'Veriler başarıyla senkronize edildi.',
    syncError: 'Senkronizasyon sırasında hata oluştu.',
    noInternetConnection: 'İnternet bağlantınız bulunmuyor. Bazı özellikler çalışmayabilir.',
    exportData: 'Verileri Dışa Aktar',
    exportChildData: 'Çocuğun Verilerini Dışa Aktar (JSON)',
    legal: 'Yasal Bilgiler',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfService: 'Hizmet Şartları',
    noRecentObservations: 'Yakın zamanda gözlem yok.',
    childNotFound: 'Çocuk bulunamadı.',
    pendingSync: 'Senkronizasyon bekleniyor.',
    developmentSummary: 'Gelişim Özeti',
    developmentReport: 'Gelişim Raporu',
    reportDate: 'Rapor Tarihi',
    childInfo: 'Çocuk Bilgileri',
    fullName: 'Tam Adı',
    aiSummariesAndSuggestions: 'Yapay Zeka Özetleri ve Öneriler',
    noAssessmentsForReport: 'Rapor için değerlendirme yok.',
    observationDate: 'Gözlem Tarihi',
    aiSummary: 'Yapay Zeka Özeti',
    observationSavedOffline: 'Gözlem çevrimdışı kaydedildi.',
    observationsSynced: 'Gözlemler senkronize edildi.',
    exportDataDescription: 'Tüm verilerinizi JSON olarak dışa Aktarın.',
    exportAllData: 'Tüm Verileri Dışa Aktar',
    // Media
    products: 'Ürünler',
    // ChildForm & ChildDetailScreen additions
    selectValidImage: 'Lütfen geçerli bir resim dosyası seçin.',
    fileTooLarge: 'Dosya boyutu çok büyük. Maksimum 10MB olmalıdır.',
    profilePhoto: 'Profil Fotoğrafı',
    retakePhoto: 'Yeniden Çek',
    deletePhoto: 'Fotoğrafı Sil',
    takeWithCamera: 'Kamera ile Çek',
    uploadFromFile: 'Dosyadan Yükle',
    changePhoto: 'Fotoğrafı Değiştir',
    lowRisk: 'Düşük Risk',
    mediumRisk: 'Orta Risk',
    highRisk: 'Yüksek Risk',
    unknown: 'Belirsiz',
    notAddedYet: 'Henüz eklenmedi.',
    interestsSection: 'İlgi Alanları',
    strengthsSection: 'Güçlü Yönler',
    guardiansSection: 'Veli ve İletişim Bilgileri',
    noGuardiansAdded: 'Veli bilgisi eklenmemiş.',
    age: 'Yaş',
    enrollmentDate: 'Kayıt Tarihi',
    importantNotes: 'Önemli Notlar',
    aiInsights: 'Yapay Zekâ Öngörüleri',
    goalsLoadError: 'Hedefler yüklenemedi',
    goalsLoading: 'Hedefler yükleniyor...',
    developmentGoals: 'Gelişim Hedefleri',
    addGoal: 'Hedef Ekle',
    addNewGoal: 'Yeni Hedef Ekle',
    goalTitle: 'Hedef Başlığı',
    goalTitlePlaceholder: 'Örn: 10 kelime öğrenme',
    developmentArea: 'Gelişim Alanı',
    priority: 'Öncelik',
    priorityLow: 'Düşük',
    priorityMedium: 'Orta',
    priorityHigh: 'Yüksek',
    targetDate: 'Hedef Tarihi',
    descriptionLabel: 'Açıklama',
    descriptionPlaceholder: 'Hedef hakkında detaylı açıklama...',
    statusCompleted: 'Tamamlandı',
    statusInProgress: 'Devam Ediyor',
    statusNotStarted: 'Başlamadı',
    statusCancelled: 'İptal Edildi',
    noGoalsYet: 'Henüz hedef belirlenmemiş.',
    addGoalHint: 'Yukarıdaki butondan yeni hedef ekleyebilirsiniz.',
    attachPhotoOptional: 'Ek Fotoğraf (isteğe bağlı)',
    present: 'Geldi',
    absent: 'Gelmedi',
    late: 'Geç',
    allItems: 'Tümü',
    fullList: 'Tüm Liste',
    studentsShown: 'öğrenci gösteriliyor',
    theme: 'Tema',
    lightTheme: 'Açık',
    darkTheme: 'Koyu',
    // PDF Report
    pdfTeacher: 'Öğretmen',
    pdfSchool: 'Okul',
    pdfReport: 'Rapor',
    pdfTitle: 'Gelişim Raporu',
    pdfProductMedia: 'Ürün / Medya',
    pdfObservation: 'Gözlem',
    pdfObservationNote: 'Gözlem Notu',
    pdfAiSummary: 'Yapay Zekâ Özeti',
    pdfSuggestions: 'Öğretmene Öneriler',
    pdfBirth: 'Doğum',
    pdfAge: 'Yaş',
    pdfClass: 'Sınıf',
    pdfNoObservations: 'Gözlem bulunamadı.',
    pdfYears: 'yıl',
    pdfMonths: 'ay',
    filtering: 'Filtreleniyor',
    // Class Detail Page
    classLabel: 'Sınıf:',
    pinned: 'Sabit',
    last7daysObs: 'Son 7 Gün Gözlem',
    last7daysProducts: 'Son 7 Gün Ürün',
    searchChild: 'Çocuk Ara',
    nameSurnamePlaceholder: 'Ad Soyad...',
    developmentTrend: 'Gelişim Alanı Trendi (8 Hafta)',
    deleteClassConfirm: '"{classroom}" sınıfını silmek istediğinize emin misiniz?',
    deleteClassConfirmWithChildren: '"{classroom}" sınıfını silmek istediğinize emin misiniz?\n\nBu işlem {childCount} çocuğu ve tüm gözlem/ürün kayıtlarını kalıcı olarak silecektir!',
    classDeleting: 'Sınıf siliniyor...',
    // Settings Page
    changeLanguageDesc: 'Uygulama dilini değiştirin.',
    createDemoData: 'Demo Verisi Oluştur',
    demoDataDesc: 'Mevcut hesabınıza örnek sınıf, çocuk, gözlem ve ürün fotoğrafları ekler.',
    classCount: 'Sınıf sayısı (1–5)',
    childrenPerClass: 'Sınıf başına çocuk',
    obsPerChild: 'Çocuk başına gözlem',
    mediaPerChild: 'Çocuk başına ürün',
    starting: 'Başlıyor...',
    completed: 'Tamamlandı.',
    errorPrefix: 'Hata:',
    unknown: 'bilinmiyor',
    creating: 'Oluşturuluyor...',
    createDemoBtn: 'Demo Verisini Oluştur',
    demoNote: 'Not: İşlem internet hızına göre zaman alabilir.',
    confirmRemoveDemo: 'Demo verileri kaldırılacak. Devam edilsin mi?',
    removing: 'Kaldırılıyor...',
    removeDemoBtn: 'Demo Verisini Geri Al',
    aiInsightsDesc: 'Hesabınızdaki gözlemler için eksik/yer tutucu (fallback) analizleri yeniden oluşturur.',
    recomputeBtn: 'Tüm Çocuklar İçin Yeniden Oluştur',
    recomputeSuccess: 'Tamamlandı. Çocuk sayfalarında Yenile\'ye gerek kalmadan öneriler görünür.',
    advancedOps: 'Gelişmiş İşlemler',
    exportToExcel: 'Excele Aktar (CSV)',
    exportDesc: 'Tüm çocuk verilerinizi Excel formatında (CSV) dışa aktarın.',
    exportNote: 'Türkçe karakterler korunur, Excelde düzenleme ve analiz yapabilirsiniz.',
    preparingData: 'Veriler hazırlanıyor...',
    noChildrenToExport: 'Dışa aktarılacak çocuk bulunamadı.',
    preparingChildren: 'çocuk verisi hazırlanıyor...',
    downloadCompleted: 'Tamamlandı! çocuk için Excel dosyası indirildi.',
    preparing: 'Hazırlanıyor...',
    exportBtn: 'Excele Aktar',
    exportCsvNote: '* Tek bir CSV dosyası indirilecek, Excelde açılabilir.',
    totalObservations: 'Toplam Gözlem',
    mediaCount: 'Ürün/Medya Sayısı',
    lastObservation: 'Son Gözlem',
    consentYes: 'Var',
    consentPending: 'Bekliyor',
    uploadProduct: 'Ürün Yükle',
    noProductsAdded: 'Henüz ürün eklenmedi.',
    productName: 'Ürün Adı',
    productDescription: 'Ürün Hakkında Not',
    productDomain: 'İlgili Beceri Alanı',
    selectFile: 'Medya Seç',
    fileSelected: 'Dosya Seçildi:',
    noFileSelected: 'Henüz dosya seçilmedi.',
    productNamePlaceholder: 'Örn: Renkli Bloklarla Yapılan Kule',
    productDescriptionPlaceholder: 'Kısa açıklama...',
    selectDomainPrompt: 'Bir gelişim alanı seçin...',
    confirmDeleteTitle: 'Kaydı Sil',
    confirmDeleteMessage: 'Bu kaydı silmek istiyor musunuz?',
    yes: 'Evet',
    no: 'Hayır',
    deleteSuccess: 'Gözlem silindi.',
    productDeleteSuccess: 'Ürün silindi.',
    // Add Child
    basicInfo: 'Temel Bilgiler',
    guardians: 'Veli Bilgileri',
    healthInfo: 'Sağlık Bilgileri',
    otherInfo: 'Diğer Bilgiler',
    addGuardian: 'Veli Ekle',
    guardianName: 'Adı Soyadı',
    guardianRelation: 'Yakınlığı',
    guardianPhone: 'Telefon',
    guardianEmail: 'E-posta',
    removeGuardian: 'Kaldır',
    allergies: 'Alerjiler (virgül ile ayırın)',
    healthNotes: 'Önemli Sağlık Notları',
    interests: 'İlgi Alanları',
    strengths: 'Güçlü Yönler',
    editChild: 'Çocuk Bilgilerini Düzenle',
    updateSuccess: 'Güncellendi.',
    confirmDeleteChildTitle: 'Çocuğu Sil',
    confirmDeleteChildMessage: 'Bu çocuğu ve ilişkili verileri silmek istiyor musunuz?',
    childDeleteSuccess: 'Silindi.',
    // Header buttons
    editClass: 'Düzenle',
    pdfDownload: 'PDF İndir',
    backToClasses: 'Sınıflara Dön',
    // Teacher profile
    teacherFirstName: 'Öğretmen Adı',
    teacherLastName: 'Öğretmen Soyadı',
    schoolName: 'Okul Adı',
    missingTeacherFields: 'Lütfen ad, soyad ve okul adını girin.',
    profileUpdateSuccess: 'Profil güncellendi.',
    // Getting Started
    gettingStarted: 'Başlarken',
    // New translations for i18n
    language: 'Dil',
    classes: 'Sınıflar',
    attendance: 'Yoklama',
    aiAssistant: 'Yapay Zekâ Asistanı',
    earlyChildhoodSystem: 'Erken Çocukluk Gözlem Sistemi',
    welcomeBack: 'Hoş geldin',
    today: 'Bugün',
    activity7days: 'Aktivite (7 gün)',
    viewChild: 'Çocuğa Git',
    pinnedChildren: 'Sabitlenen Çocuklar',
    newChat: 'Yeni Sohbet',
    chats: 'Sohbetler',
    noChatYet: 'Henüz sohbet yok.',
    general: 'Genel',
    child: 'Çocuk',
    selectClass: 'Sınıf seçin…',
    selectChild: 'Çocuk seçin…',
    typeMessage: 'Mesajınızı yazın…',
    send: 'Gönder',
    assistantTyping: 'Asistan yazıyor…',
    noteDisclaimer: 'Not: Tıbbi tanı koymaz; pratik sınıf içi öneriler sunar.',
    classCount: 'Sınıf sayısı',
    childrenPerClass: 'Sınıf başına çocuk',
    obsPerChild: 'Çocuk başına gözlem',
    mediaPerChild: 'Çocuk başına ürün',
    createClass: 'Sınıf Oluştur',
    noClassFound: 'Sınıf bulunamadı. Üstten yeni sınıf oluşturabilirsiniz.',
    allChildren: 'Tüm Çocuklar',
    editClassTitle: 'Sınıfı Düzenle',
    className: 'Sınıf Adı',
    color: 'Renk',
    pinClass: 'Sınıfı sabitle',
    deleteClass: 'Sınıfı Sil',
    deletingClass: 'Sınıf siliniyor...',
    filterClass: 'Sınıf Filtrele',
    allClasses: 'Tüm Sınıflar',
    classReport: 'Sınıf Raporu',
    aiSuggestionsForClass: 'Sınıf için Yapay Zekâ Önerileri',
    nameSurname: 'Ad Soyad',
    childrenList: 'Çocuklar',
    saveChildrenPortfolio: 'Çocukların ürünlerini ve gelişimini dijital ortamda saklayın',
    selectClassFirst: 'Lütfen bir sınıf seçin. Önce Sınıflar sayfasından sınıf oluşturmanız gerekebilir.',
    createClassFirst: 'Önce Sınıflar sayfasından sınıf oluşturun.',
    classAddError: 'Sınıf eklenemedi',
    noChildInClass: 'Bu sınıfta çocuk yok.',
    noSuggestionsYet: 'Henüz öneri yok.',
    noData: 'Veri yok.',
    regenerateAll: 'Tüm Çocuklar İçin Yeniden Oluştur',
    generating: 'Oluşturuluyor...',
    regenerateDone: 'Tamamlandı. Çocuk sayfalarında Yenile\'ye gerek kalmadan öneriler görünür.',
    searchBox: 'Çocuk ara: üst kısımdaki arama kutusunu kullanın.',
    themeSetting: 'açık/koyu temayı',
    createClassAndChild: 'Sınıf Oluştur ve Çocuk Ekle',
    createClassDescription: 'Sol menüde Sınıflar bölümünden yeni sınıf oluşturun. Ardından Çocuklar sayfasından her sınıfa çocuk kartları ekleyin.',
    recordObservation: 'Gözlem Kaydı',
    recordObservationDescription: 'Çocuğun detay sayfasına girerek gözlem ve ürün kaydı yapın. Yazılı not veya fotoğraf/video ekleyebilirsiniz.',
    aiReports: 'Yapay Zekâ Raporları',
    aiReportsDescription: 'Çocuk veya sınıf sayfalarındaki Rapor bölümünden gelişim özetlerini görüntüleyebilir, PDF olarak indirebilirsiniz.',
    tipsTitle: 'İpuçları',
    askAnything: 'Sorunuzu yazın. Örn: "3-4 yaş grubu için ince motoru güçlendiren etkinlik önerir misin?"',
    confirmDeleteChat: 'sohbetini silmek istiyor musunuz?',
    // GettingStarted
    gettingStartedDesc: 'PortfoAI ile hızlı bir başlangıç yapmanız için kısa bir kullanım kılavuzu.',
    step1Title: '1) Sınıf Oluştur ve Çocuk Ekle',
    step1Desc: 'Sol menüde Sınıflar bölümünden yeni sınıf oluşturun. Ardından Çocuklar sayfasından her sınıfa çocuk kartları ekleyin.',
    step2Title: '2) Gözlem Ekle ve Alanları Seç',
    step2Desc: 'Bir çocuğun kartına girip Gözlem Ekle deyin. Davranışı kısa bir notla yazın, gelişim alanlarını seçin.',
    step3Title: '3) Ürün/Medya Yükle (Portfolyo)',
    step3Desc: 'Çocuğun sayfasındaki Medya sekmesinden ürün fotoğraflarını yükleyin.',
    step4Title: '4) Rapor ve PDF Alma',
    step4Desc: 'Çocuk veya sınıf sayfalarındaki Rapor bölümünden gelişim özetlerini görüntüleyebilir, PDF olarak indirebilirsiniz.',
    demoDataTip: 'İpucu: Demo Veri ile Hızlı Keşif',
    demoDataDesc: 'Ayarlar → Demo Verisi Oluştur butonuna tıklayın; örnek sınıflar ve çocuklar otomatik eklenir.',
    goToSettings: 'Ayarlar\'a Git',
    frequentActions: 'Sık Kullanılan İşlemler',
    searchChildTip: 'Çocuk ara: üst kısımdaki arama kutusunu kullanın.',
    exportDataTip: 'Veri aktarımı: Ayarlar → Verileri Dışa Aktar.',
    themeTip: 'Tema: Sol panel altından açık/koyu temayı değiştirin.',
    // Attendance
    attendanceSystem: 'Yoklama Sistemi',
    dailyAttendanceTracking: 'Günlük devam takibi ve istatistikler',
    thisMonthAttendance: 'Bu Ay Devam',
    present: 'Geldi',
    absent: 'Gelmedi',
    late: 'Geç Geldi',
    excused: 'Mazeret',
    unmarked: 'İşaretlenmedi',
    filtering: 'Filtreleniyor',
    allList: 'Tüm Liste',
    selectDate: 'Tarih Seç',
    quickAction: 'Hızlı İşlem',
    markAllPresent: 'Hepsini Geldi İşaretle',
    markAllAbsent: 'Hepsini Gelmedi İşaretle',
    clearFilter: 'Filtreyi Temizle',
    showAll: 'Tüm Listeyi Göster',
    studentList: 'Öğrenci Listesi',
    showingStudents: 'öğrenci gösteriliyor',
    showAllList: 'Tümünü Göster',
    photo: 'Fotoğraf',
    status: 'Durum',
    action: 'İşlem',
    noStudentFound: 'Hiç çocuk bulunamadı.',
    noStudentInStatus: 'durumunda öğrenci bulunamadı.',
    saveAttendance: 'Yoklamayı Kaydet',
    savingAttendance: 'Kaydediliyor...',
    attendanceSaved: 'Yoklama başarıyla kaydedildi!',
    attendanceSaveFailed: 'Yoklama kaydedilemedi',
    dataLoadFailed: 'Veri yüklenemedi',
  },
  en: {
    appName: 'PortfoAI',
    // Auth
    signInTitle: 'Sign In',
    signUpTitle: 'Create Account',
    signInDescription: 'Enter your email and password to access your account.',
    signUpDescription: 'Create a new account to get started.',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    signInAction: 'Sign In',
    signUpAction: 'Sign Up',
    noAccountPrompt: "Don't have an account?",
    haveAccountPrompt: 'Already have an account?',
    switchToSignUp: 'Sign Up',
    switchToSignIn: 'Sign In',
    signUpSuccess: 'Account created! Please verify your email.',
    apiKeyError: 'Supabase API key is invalid or missing.',
    // General
    dashboard: 'Dashboard',
    children: 'Children',
    observations: 'Observations',
    settings: 'Settings',
    signOut: 'Sign Out',
    welcome: 'Welcome',
    // Landing / Auth
    landingHero: 'Professionally track child development with AI-powered observation, analysis, and portfolio management.',
    smartAnalysisTitle: 'Smart Analysis',
    smartAnalysisDesc: 'Automated evaluation and suggestions with AI',
    digitalPortfolioTitle: 'Digital Portfolio',
    digitalPortfolioDesc: 'Store children\'s work and development digitally',
    anyDeviceTitle: 'Access Anywhere',
    anyDeviceDesc: 'Easily access from phone, tablet, or computer',
    createAccountTitle: 'Create Account',
    welcomeTitle: 'Welcome',
    createAccountDesc: 'Create a new account to get started',
    signInDesc: 'Sign in to your account',
    yourName: 'First Name',
    yourSurname: 'Last Name',
    schoolName: 'School Name',
    secureSSL: 'SSL Encrypted',
    secureBadge: 'Secure',
    fastBadge: 'Fast',
    footerRights: '© 2025 PortfoAI - All rights reserved',
    haveAccountBtn: 'Already have an account? Sign in',
    noAccountBtn: 'Don\'t have an account? Sign up',
    missingTeacherFields: 'Please fill in name, surname, and school fields.',
    recentObservations: 'Recent Observations',
    quickAccess: 'Quick Access',
    addChild: 'Add Child',
    addObservation: 'Add Observation',
    editObservation: 'Edit Observation',
    childList: 'Child List',
    searchChild: 'Search child...',
    noChildrenFound: 'No children added yet.',
    childProfile: 'Child Profile',
    firstName: 'First Name',
    lastName: 'Last Name',
    dob: 'Date of Birth',
    age: 'Age',
    classroom: 'Classroom',
    parentalConsent: 'Parental Consent Obtained',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    newObservationFor: 'New Observation for',
    observationNote: 'Observation Note',
    notePlaceholder: 'Detailed notes about the child\'s behaviors, words, and interactions...',
    developmentDomains: 'Skill Areas',
    selectDomains: 'Select relevant skill areas',
    context: 'Context',
    tags: 'Tags',
    tagsPlaceholder: 'Add tags separated by commas',
    addMedia: 'Add Photo/Video',
    submitObservation: 'Save Observation',
    consentYes: 'Yes',
    consentNo: 'No',
    childDetail: 'Child Details',
    profile: 'Profile',
    development: 'Development',
    media: 'Media',
    generateReport: 'Generate Development Report',
    aiAnalysis: 'AI Analysis',
    getAnalysis: 'Get Analysis',
    summary: 'Summary',
    riskLevel: 'Risk Level',
    suggestions: 'Suggestions for Teacher',
    domainScores: 'Domain Scores',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    loading: 'Loading...',
    deleting: 'Deleting...',
    errorOccurred: 'An error occurred.',
    offlineWarning: 'You are offline.',
    syncAttempt: 'Syncing data...',
    syncSuccess: 'Data synced successfully.',
    syncError: 'Error during synchronization.',
    noInternetConnection: 'No internet connection. Some features may not work.',
    exportData: 'Export Data',
    exportChildData: 'Export Child Data (JSON)',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    noRecentObservations: 'No recent observations.',
    childNotFound: 'Child not found.',
    pendingSync: 'Sync pending.',
    developmentSummary: 'Development Summary',
    developmentReport: 'Development Report',
    reportDate: 'Report Date',
    childInfo: 'Child Information',
    fullName: 'Full Name',
    aiSummariesAndSuggestions: 'AI Summaries and Suggestions',
    noAssessmentsForReport: 'No assessments for report.',
    observationDate: 'Observation Date',
    aiSummary: 'AI Summary',
    observationSavedOffline: 'Observation saved offline.',
    observationsSynced: 'Observations synced.',
    exportDataDescription: 'Export all your data as JSON.',
    exportAllData: 'Export All Data',
    // Media
    products: 'Products',
    // ChildForm & ChildDetailScreen additions
    selectValidImage: 'Please select a valid image file.',
    fileTooLarge: 'File size too large. Maximum 10MB.',
    profilePhoto: 'Profile Photo',
    retakePhoto: 'Retake',
    deletePhoto: 'Delete Photo',
    takeWithCamera: 'Take with Camera',
    uploadFromFile: 'Upload from File',
    changePhoto: 'Change Photo',
    lowRisk: 'Low Risk',
    mediumRisk: 'Medium Risk',
    highRisk: 'High Risk',
    unknown: 'Unknown',
    notAddedYet: 'Not added yet.',
    interestsSection: 'Interests',
    strengthsSection: 'Strengths',
    guardiansSection: 'Guardian & Contact Information',
    noGuardiansAdded: 'No guardian information added.',
    age: 'Age',
    enrollmentDate: 'Enrollment Date',
    importantNotes: 'Important Notes',
    aiInsights: 'AI Insights',
    goalsLoadError: 'Could not load goals',
    goalsLoading: 'Loading goals...',
    developmentGoals: 'Development Goals',
    addGoal: 'Add Goal',
    addNewGoal: 'Add New Goal',
    goalTitle: 'Goal Title',
    goalTitlePlaceholder: 'E.g.: Learn 10 words',
    developmentArea: 'Development Area',
    priority: 'Priority',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    targetDate: 'Target Date',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Detailed description about the goal...',
    statusCompleted: 'Completed',
    statusInProgress: 'In Progress',
    statusNotStarted: 'Not Started',
    statusCancelled: 'Cancelled',
    noGoalsYet: 'No goals set yet.',
    addGoalHint: 'You can add a new goal using the button above.',
    attachPhotoOptional: 'Attach Photo (optional)',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    allItems: 'All',
    fullList: 'Full List',
    studentsShown: 'students shown',
    theme: 'Theme',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    // PDF Report
    pdfTeacher: 'Teacher',
    pdfSchool: 'School',
    pdfReport: 'Report',
    pdfTitle: 'Development Report',
    pdfProductMedia: 'Product / Media',
    pdfObservation: 'Observation',
    pdfObservationNote: 'Observation Note',
    pdfAiSummary: 'AI Summary',
    pdfSuggestions: 'Suggestions for Teacher',
    pdfBirth: 'Birth',
    pdfAge: 'Age',
    pdfClass: 'Class',
    pdfNoObservations: 'No observations found.',
    pdfYears: 'years',
    pdfMonths: 'months',
    filtering: 'Filtering',
    // Class Detail Page
    classLabel: 'Class:',
    pinned: 'Pinned',
    last7daysObs: 'Last 7 Days Obs.',
    last7daysProducts: 'Last 7 Days Products',
    searchChild: 'Search Child',
    nameSurnamePlaceholder: 'Name Surname...',
    developmentTrend: 'Development Area Trend (8 Weeks)',
    deleteClassConfirm: 'Are you sure you want to delete the class "{classroom}"?',
    deleteClassConfirmWithChildren: 'Are you sure you want to delete the class "{classroom}"?\n\nThis will permanently delete {childCount} children and all their observation/product records!',
    classDeleting: 'Deleting class...',
    // Settings Page
    changeLanguageDesc: 'Change application language.',
    createDemoData: 'Create Demo Data',
    demoDataDesc: 'Adds sample classes, children, observations and product photos to your account.',
    classCount: 'Number of classes (1–5)',
    childrenPerClass: 'Children per class',
    obsPerChild: 'Observations per child',
    mediaPerChild: 'Products per child',
    starting: 'Starting...',
    completed: 'Completed.',
    errorPrefix: 'Error:',
    unknown: 'unknown',
    creating: 'Creating...',
    createDemoBtn: 'Create Demo Data',
    demoNote: 'Note: This may take time depending on internet speed.',
    confirmRemoveDemo: 'Demo data will be removed. Continue?',
    removing: 'Removing...',
    removeDemoBtn: 'Remove Demo Data',
    aiInsightsDesc: 'Regenerates missing/placeholder analyses for observations in your account.',
    recomputeBtn: 'Regenerate for All Children',
    recomputeSuccess: 'Completed. Suggestions will appear on child pages without needing to refresh.',
    advancedOps: 'Advanced Operations',
    exportToExcel: 'Export to Excel (CSV)',
    exportDesc: 'Export all child data in Excel format (CSV).',
    exportNote: 'Turkish characters are preserved, you can edit and analyze in Excel.',
    preparingData: 'Preparing data...',
    noChildrenToExport: 'No children found to export.',
    preparingChildren: 'child data being prepared...',
    downloadCompleted: 'Completed! Excel file downloaded for children.',
    preparing: 'Preparing...',
    exportBtn: 'Export to Excel',
    exportCsvNote: '* A single CSV file will be downloaded, can be opened in Excel.',
    totalObservations: 'Total Observations',
    mediaCount: 'Product/Media Count',
    lastObservation: 'Last Observation',
    consentYes: 'Yes',
    consentPending: 'Pending',
    uploadProduct: 'Upload Product',
    noProductsAdded: 'No products added yet.',
    productName: 'Product Name',
    productDescription: 'Notes About Product',
    productDomain: 'Related Skill Area',
    selectFile: 'Select Media',
    fileSelected: 'File Selected:',
    noFileSelected: 'No file selected yet.',
    productNamePlaceholder: 'E.g.: Tower Made with Colorful Blocks',
    productDescriptionPlaceholder: 'Brief description...',
    selectDomainPrompt: 'Select a skill area...',
    confirmDeleteTitle: 'Delete Record',
    confirmDeleteMessage: 'Do you want to delete this record?',
    yes: 'Yes',
    no: 'No',
    deleteSuccess: 'Observation deleted.',
    productDeleteSuccess: 'Product deleted.',
    // Add Child
    basicInfo: 'Basic Information',
    guardians: 'Guardian Information',
    healthInfo: 'Health Information',
    otherInfo: 'Other Information',
    addGuardian: 'Add Guardian',
    guardianName: 'Full Name',
    guardianRelation: 'Relationship',
    guardianPhone: 'Phone',
    guardianEmail: 'Email',
    removeGuardian: 'Remove',
    allergies: 'Allergies (separate with commas)',
    healthNotes: 'Important Health Notes',
    interests: 'Interests',
    strengths: 'Strengths',
    editChild: 'Edit Child Information',
    updateSuccess: 'Updated.',
    confirmDeleteChildTitle: 'Delete Child',
    confirmDeleteChildMessage: 'Do you want to delete this child and all related data?',
    childDeleteSuccess: 'Deleted.',
    // Header buttons
    editClass: 'Edit',
    pdfDownload: 'Download PDF',
    backToClasses: 'Back to Classes',
    // Teacher profile
    teacherFirstName: 'Teacher First Name',
    teacherLastName: 'Teacher Last Name',
    schoolName: 'School Name',
    missingTeacherFields: 'Please enter first name, last name, and school name.',
    profileUpdateSuccess: 'Profile updated.',
    // Getting Started
    gettingStarted: 'Getting Started',
    // New translations for i18n
    language: 'Language',
    classes: 'Classes',
    attendance: 'Attendance',
    aiAssistant: 'AI Assistant',
    earlyChildhoodSystem: 'Early Childhood Observation System',
    welcomeBack: 'Welcome back',
    today: 'Today',
    activity7days: 'Activity (7 days)',
    viewChild: 'Go to Child',
    pinnedChildren: 'Pinned Children',
    newChat: 'New Chat',
    chats: 'Chats',
    noChatYet: 'No chats yet.',
    general: 'General',
    child: 'Child',
    selectClass: 'Select class...',
    selectChild: 'Select child...',
    typeMessage: 'Type your message...',
    send: 'Send',
    assistantTyping: 'Assistant is typing...',
    noteDisclaimer: 'Note: Does not provide medical diagnoses; offers practical classroom suggestions.',
    classCount: 'Number of classes',
    childrenPerClass: 'Children per class',
    obsPerChild: 'Observations per child',
    mediaPerChild: 'Products per child',
    createClass: 'Create Class',
    noClassFound: 'No classes found. You can create a new class above.',
    allChildren: 'All Children',
    editClassTitle: 'Edit Class',
    className: 'Class Name',
    color: 'Color',
    pinClass: 'Pin this class',
    deleteClass: 'Delete Class',
    deletingClass: 'Deleting class...',
    filterClass: 'Filter by Class',
    allClasses: 'All Classes',
    classReport: 'Class Report',
    aiSuggestionsForClass: 'AI Suggestions for Class',
    nameSurname: 'Name',
    childrenList: 'Children',
    saveChildrenPortfolio: 'Store children\'s products and development digitally',
    selectClassFirst: 'Please select a class. You may need to create a class from the Classes page first.',
    createClassFirst: 'Create a class from the Classes page first.',
    classAddError: 'Could not add class',
    noChildInClass: 'No children in this class.',
    noSuggestionsYet: 'No suggestions yet.',
    noData: 'No data.',
    regenerateAll: 'Regenerate for All Children',
    generating: 'Generating...',
    regenerateDone: 'Done. Suggestions will appear on child pages without needing to refresh.',
    searchBox: 'Search child: use the search box at the top.',
    themeSetting: 'light/dark theme',
    createClassAndChild: 'Create Class and Add Child',
    createClassDescription: 'Create a new class from the Classes section in the left menu. Then add child cards to each class from the Children page.',
    recordObservation: 'Record Observation',
    recordObservationDescription: 'Enter the child\'s detail page to record observations and products. You can add written notes or photos/videos.',
    aiReports: 'AI Reports',
    aiReportsDescription: 'View development summaries from the Report section on child or class pages, and download as PDF.',
    tipsTitle: 'Tips',
    askAnything: 'Type your question. E.g.: "Can you suggest activities to strengthen fine motor skills for 3-4 year olds?"',
    confirmDeleteChat: 'chat? Are you sure you want to delete this',
    // GettingStarted
    gettingStartedDesc: 'A quick guide to help you get started with PortfoAI.',
    step1Title: '1) Create Class and Add Child',
    step1Desc: 'Create a new class from the Classes section in the left menu. Then add child cards to each class from the Children page.',
    step2Title: '2) Add Observation and Select Areas',
    step2Desc: 'Click on a child card and select Add Observation. Write a brief note about the behavior and select development areas.',
    step3Title: '3) Upload Product/Media (Portfolio)',
    step3Desc: 'Upload product photos from the Media tab on the child page.',
    step4Title: '4) Get Report and PDF',
    step4Desc: 'View development summaries from the Report section on child or class pages, and download as PDF.',
    demoDataTip: 'Tip: Quick Exploration with Demo Data',
    demoDataDesc: 'Click Settings → Create Demo Data; sample classes and children will be added automatically.',
    goToSettings: 'Go to Settings',
    frequentActions: 'Frequent Actions',
    searchChildTip: 'Search child: use the search box at the top.',
    exportDataTip: 'Data export: Settings → Export Data.',
    themeTip: 'Theme: Change light/dark theme from the bottom of the left panel.',
    // Attendance
    attendanceSystem: 'Attendance System',
    dailyAttendanceTracking: 'Daily attendance tracking and statistics',
    thisMonthAttendance: 'This Month Attendance',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    excused: 'Excused',
    unmarked: 'Unmarked',
    filtering: 'Filtering',
    allList: 'All List',
    selectDate: 'Select Date',
    quickAction: 'Quick Action',
    markAllPresent: 'Mark All Present',
    markAllAbsent: 'Mark All Absent',
    clearFilter: 'Clear Filter',
    showAll: 'Show All',
    studentList: 'Student List',
    showingStudents: 'students showing',
    showAllList: 'Show All',
    photo: 'Photo',
    status: 'Status',
    action: 'Action',
    noStudentFound: 'No children found.',
    noStudentInStatus: 'No students found with status',
    saveAttendance: 'Save Attendance',
    savingAttendance: 'Saving...',
    attendanceSaved: 'Attendance saved successfully!',
    attendanceSaveFailed: 'Could not save attendance',
    dataLoadFailed: 'Could not load data',
  }
};

export const t = (key: string): string =>
  translations[currentLanguage][key] || translations['tr'][key] || key;
